# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'health_center_dialog.ui'
#
# Created: Wed Jun 29 15:53:48 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_HealthCenterDialog(object):
    def setupUi(self, HealthCenterDialog):
        HealthCenterDialog.setObjectName(_fromUtf8("HealthCenterDialog"))
        HealthCenterDialog.resize(600, 400)
        HealthCenterDialog.setMinimumSize(QtCore.QSize(600, 400))
        HealthCenterDialog.setMaximumSize(QtCore.QSize(600, 400))
        self.formLayout = QtGui.QFormLayout(HealthCenterDialog)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.nameLabel = QtGui.QLabel(HealthCenterDialog)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtGui.QLineEdit(HealthCenterDialog)
        self.nameLineEdit.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nameLineEdit)
        self.typeLabel = QtGui.QLabel(HealthCenterDialog)
        self.typeLabel.setObjectName(_fromUtf8("typeLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.typeLabel)
        self.typeComboBox = QtGui.QComboBox(HealthCenterDialog)
        self.typeComboBox.setObjectName(_fromUtf8("typeComboBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.typeComboBox)
        self.descriptionLabel = QtGui.QLabel(HealthCenterDialog)
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.descriptionLabel)
        self.descriptionTextEdit = QtGui.QTextEdit(HealthCenterDialog)
        self.descriptionTextEdit.setObjectName(_fromUtf8("descriptionTextEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.descriptionTextEdit)
        self.latitudeLabel = QtGui.QLabel(HealthCenterDialog)
        self.latitudeLabel.setObjectName(_fromUtf8("latitudeLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.latitudeLabel)
        self.latitudeLineEdit = QtGui.QLineEdit(HealthCenterDialog)
        self.latitudeLineEdit.setEnabled(True)
        self.latitudeLineEdit.setReadOnly(False)
        self.latitudeLineEdit.setObjectName(_fromUtf8("latitudeLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.latitudeLineEdit)
        self.longitudeLabel = QtGui.QLabel(HealthCenterDialog)
        self.longitudeLabel.setObjectName(_fromUtf8("longitudeLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.longitudeLabel)
        self.longitudeLineEdit = QtGui.QLineEdit(HealthCenterDialog)
        self.longitudeLineEdit.setEnabled(True)
        self.longitudeLineEdit.setReadOnly(False)
        self.longitudeLineEdit.setObjectName(_fromUtf8("longitudeLineEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.longitudeLineEdit)
        self.nameResponsibleLabel = QtGui.QLabel(HealthCenterDialog)
        self.nameResponsibleLabel.setObjectName(_fromUtf8("nameResponsibleLabel"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.nameResponsibleLabel)
        self.nameResponsibleLineEdit = QtGui.QLineEdit(HealthCenterDialog)
        self.nameResponsibleLineEdit.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.nameResponsibleLineEdit.setObjectName(_fromUtf8("nameResponsibleLineEdit"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.nameResponsibleLineEdit)
        self.phoneNumberlabel = QtGui.QLabel(HealthCenterDialog)
        self.phoneNumberlabel.setObjectName(_fromUtf8("phoneNumberlabel"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.LabelRole, self.phoneNumberlabel)
        self.phoneNumberLineEdit = QtGui.QLineEdit(HealthCenterDialog)
        self.phoneNumberLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.phoneNumberLineEdit.setObjectName(_fromUtf8("phoneNumberLineEdit"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.FieldRole, self.phoneNumberLineEdit)
        self.emailAddressLabel = QtGui.QLabel(HealthCenterDialog)
        self.emailAddressLabel.setObjectName(_fromUtf8("emailAddressLabel"))
        self.formLayout.setWidget(17, QtGui.QFormLayout.LabelRole, self.emailAddressLabel)
        self.emailAddressLineEdit = QtGui.QLineEdit(HealthCenterDialog)
        self.emailAddressLineEdit.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.emailAddressLineEdit.setObjectName(_fromUtf8("emailAddressLineEdit"))
        self.formLayout.setWidget(17, QtGui.QFormLayout.FieldRole, self.emailAddressLineEdit)
        self.buttonBox = QtGui.QDialogButtonBox(HealthCenterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout.setWidget(18, QtGui.QFormLayout.FieldRole, self.buttonBox)
        self.locateOnMapPushButton = QtGui.QPushButton(HealthCenterDialog)
        self.locateOnMapPushButton.setObjectName(_fromUtf8("locateOnMapPushButton"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.locateOnMapPushButton)
        self.nameLabel.setBuddy(self.nameLineEdit)
        self.typeLabel.setBuddy(self.typeComboBox)
        self.descriptionLabel.setBuddy(self.descriptionTextEdit)
        self.latitudeLabel.setBuddy(self.latitudeLineEdit)
        self.longitudeLabel.setBuddy(self.longitudeLineEdit)
        self.nameResponsibleLabel.setBuddy(self.nameResponsibleLineEdit)
        self.phoneNumberlabel.setBuddy(self.phoneNumberLineEdit)
        self.emailAddressLabel.setBuddy(self.emailAddressLineEdit)

        self.retranslateUi(HealthCenterDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), HealthCenterDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), HealthCenterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(HealthCenterDialog)
        HealthCenterDialog.setTabOrder(self.nameLineEdit, self.typeComboBox)
        HealthCenterDialog.setTabOrder(self.typeComboBox, self.descriptionTextEdit)
        HealthCenterDialog.setTabOrder(self.descriptionTextEdit, self.latitudeLineEdit)
        HealthCenterDialog.setTabOrder(self.latitudeLineEdit, self.longitudeLineEdit)
        HealthCenterDialog.setTabOrder(self.longitudeLineEdit, self.nameResponsibleLineEdit)
        HealthCenterDialog.setTabOrder(self.nameResponsibleLineEdit, self.phoneNumberLineEdit)
        HealthCenterDialog.setTabOrder(self.phoneNumberLineEdit, self.emailAddressLineEdit)
        HealthCenterDialog.setTabOrder(self.emailAddressLineEdit, self.buttonBox)

    def retranslateUi(self, HealthCenterDialog):
        HealthCenterDialog.setWindowTitle(QtGui.QApplication.translate("HealthCenterDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("HealthCenterDialog", "&Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.typeLabel.setText(QtGui.QApplication.translate("HealthCenterDialog", "&Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionLabel.setText(QtGui.QApplication.translate("HealthCenterDialog", "&Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeLabel.setText(QtGui.QApplication.translate("HealthCenterDialog", "&Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeLabel.setText(QtGui.QApplication.translate("HealthCenterDialog", "L&ongitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.nameResponsibleLabel.setText(QtGui.QApplication.translate("HealthCenterDialog", "Name of the &Responsible Person:", None, QtGui.QApplication.UnicodeUTF8))
        self.phoneNumberlabel.setText(QtGui.QApplication.translate("HealthCenterDialog", "&Phone Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.emailAddressLabel.setText(QtGui.QApplication.translate("HealthCenterDialog", "&Email Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.locateOnMapPushButton.setText(QtGui.QApplication.translate("HealthCenterDialog", "Locate Lat/Lng on map", None, QtGui.QApplication.UnicodeUTF8))

